### ISSUE TITLE
Unable to flash the EEPROM_WIPE.bin

### ISSUE THREAD

**Issue by gabrielebesta** [nicsure/TDH3Flash#1]
The tool cannot flash the **EEPROM_WIPE.bin** firmware due to the following error.
```
TD-H3 Firmware Flasher

EEPROM_WIPE.bin is not the correct size to be a valid firmware file
```

**Comment by nicsure** [comment]
Just change the lower file size limit and recompile. Or bolt on some padding to the end of the bin.
